version: '3'
services: # UI_Server
  frontend:
    build:
      context: ./UI_Server/client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./UI_Server/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
  # Computing_Server
  computing:
    build:
      context: ./Computing_Server
      dockerfile: Dockerfile
    ports:
      - "5000:8000"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
