version: '3'
services:
  influxdb:
    image: influxdb
    container_name: my-influxdb
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=mydatabase
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_TOKEN=DYcSnm8TvuZ-rPDAPHJvNCuJZf87Um0cvqHxzVWjve32S7Xh-euMgqmdCDRMduGoOExmIuHfvt_quX7-uvkQUw==

