version: '3'
services:

  frontend:
    build:
      context: ./UI_Server/client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./UI_Server/backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
