version: '3'
services:
  influxdb:
    image: influxdb
    container_name: my-influxdb
    ports:
      - '8086:8086'
    env_file:
      - .env
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    entrypoint: ["./entrypoint.sh"]

