version: '3'
services:
# Backend containers
  parser:
    image: scd-parser
    build:
      context: .
      dockerfile: scd-parser.Dockerfile
    ports:
      - "8001:8000"

  openhab:
    image: openhab/openhab:latest
    container_name: openhab
    volumes:
      - ./openhab_addons:/openhab/addons 
      - ./openhab_conf:/openhab/conf
      - ./openhab_userdata:/openhab/userdata
    network_mode: host
    restart: always

# test network
  network-test:
    image: scd-network-test
    build:
      context: .
      dockerfile: scd-network-test.Dockerfile
    command: tail -f /dev/null
    network_mode: host

# Frontend containers
  node:
    image: scd-server
    ports:
      - "80:8000"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
