version: '3'
services:
  influxdb:
    image: influxdb:2.7.1
    #build:
     # context: .
     # dockerfile: influxdb/my_influxdb.Dockerfile
    container_name: influxdb
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
      - ./certificates/fullchain.pem:/etc/ssl/cert.crt
      - ./certificates/privkey.pem:/etc/ssl/cert.key
    env_file:
      - .env
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    container_name: telegraf
    image: telegraf:1.19
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
      - ./certificates/fullchain.pem:/etc/telegraf/cert.crt
      - ./certificates/privkey.pem:/etc/telegraf/cert.key
    env_file:
      - .env
    depends_on:
      - influxdb

  grafana:
    container_name: grafana
    image: grafana/grafana:9.4.0
    volumes:
      - grafana-storage:/var/lib/grafana:rw
      - ./grafana/config:/etc/grafana
      - ./certificates/fullchain.pem:/etc/grafana/cert.crt
      - ./certificates/privkey.pem:/etc/grafana/cert.key
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/ressources:./public/img/bg/custom
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
      - "3001:3001"

  openhab:
    image: openhab/openhab:3.4.4
    container_name: openhab
    volumes:
      - "./openhab/addons:/openhab/addons"
      - "./openhab/conf:/openhab/conf"
      - "./openhab/userdata:/openhab/userdata"
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - influxdb
    network_mode: host
  
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"


  web:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/www:/usr/share/nginx/html:ro
      - ./certificates/:/etc/ssl/certs/:ro

volumes:
  grafana-storage:
  influxdb-storage: