version: '3'
services:
  node:
    image: scd-server
    ports:
      - "80:8000"
    # Add additional configuration options for the Node container if needed
    # ...

  openhab:
    image: openhab/openhab:latest
    container_name: openhab
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./openhab_addons:/openhab/addons 
      - ./openhab_conf:/openhab/conf
      - ./openhab_userdata:/openhab/userdata

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    # Add additional configuration options for the MongoDB container if needed
    # ...
