version: '3'
services:

  frontend:
    build:
      context: ./server/client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./server/backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001

  # Backend containers
  parser:
    image: scd-parser
    build:
      dockerfile: scd-parser.Dockerfile
    ports:
      - "8001:8000"
      
  # test network
  network-test:
    image: scd-network-test
    build:
      context: .
      dockerfile: scd-network-test.Dockerfile
    command: tail -f /dev/null
    network_mode: host

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
