version: '3'
services: # UI_Server
  frontend:
    build:
      context: ./UI_Server/client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./UI_Server/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  # Computing_Server
  computing:
    build:
      context: ./Computing_Server
      dockerfile: Dockerfile
    ports:
      - "5000:8000"
    depends_on:
      - mongodb

  # DB
  mongodb:
    image: mongo:latest
    env_file:
      - ./env/mongodb.env
    ports:
      - "27017:27017"
    volumes:
      - database:/data/db
volumes:
  database: { }
