version: '3'
services:
# Backend containers
  parser:
    image: scd-parser
    build:
      context: .
      dockerfile: scd-parser.Dockerfile
    ports:
      - "8001:8000"

  openhab:
    image: openhab/openhab:3.1.0
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./openhab/conf:/openhab/conf
      - ./openhab/userdata:/openhab/userdata
      - ./openhab/addons:/openhab/addons
      
# test network
  network-test:
    image: scd-network-test
    build:
      context: .
      dockerfile: scd-network-test.Dockerfile
    command: tail -f /dev/null
    network_mode: host

# Frontend containers
  node:
    image: scd-server
    ports:
      - "80:8000"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
