{
 "title": "Home Dashboard",
 "description": "Home Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "{\"find\": \"terms\", \"field\": \"beat.name\"}"
   },
   { "name": "Interval", "query": "5s,10s,1m,2m" },
   { "name": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Solar panel energy production",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 9 },
   "targets": [
    {
     "query": "import \"regexp\"\r\n\r\nfrom(bucket: \"openhab\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^sp_[^_]+_[^_]+_power$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"item\"] =~ /^sp_[^_]+_[^_]+_power$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Windmil energy production",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "import \"regexp\"\r\n\r\nfrom(bucket: \"openhab\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^wm_[^_]+_[^_]+_power$/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"item\"] =~ /^wm_[^_]+_[^_]+_power$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "House energy consumption",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 9 },
   "targets": [
    {
     "query": "from(bucket: \"openhab\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"h_l3_1_power\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}