{
 "title": "DNIIT sensors",
 "description": "dniit sensors",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "{\"find\": \"terms\", \"field\": \"beat.name\"}"
   },
   { "name": "Interval", "query": "5s,10s,1m,2m" },
   { "name": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Humidity percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openhab\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensorTienNg_smartbuilding_1_humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openhab\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensorTienNg_smartbuilding_1_temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"openhab\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensorTienNg_smartbuilding_1_temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Illuminance",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "query": "from(bucket: \"openhab\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensorTienNg_smartbuilding_1_illuminance\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Canvas view",
   "type": "canvas",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"openhab\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensorTienNg_smartbuilding_1_humidity\")\r\n  |> last()\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> rename(columns: { _value: \"humidity\"})\r\n"
    },
    {
     "query": "from(bucket: \"openhab\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensorTienNg_smartbuilding_1_illuminance\")\r\n  |> last()\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> rename(columns: { _value: \"lum\"})\r\n"
    },
    {
     "query": "from(bucket: \"openhab\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensorTienNg_smartbuilding_1_temperature\")\r\n  |> last()\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> rename(columns: { _value: \"temp\"})\r\n"
    }
   ]
  },
  {
   "title": "All sensor values",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"openhab\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensorTienNg_smartbuilding_1_temperature\" or r[\"_measurement\"] == \"sensorTienNg_smartbuilding_1_illuminance\" or r[\"_measurement\"] == \"sensorTienNg_smartbuilding_1_humidity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "pm values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "query": "from(bucket: \"openhab\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pmSensor_smartbuilding_1_pm1\" or r[\"_measurement\"] == \"pmSensor_smartbuilding_1_pm25\" or r[\"_measurement\"] == \"pmSensor_smartbuilding_1_pm10\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Pm 10 mesurement",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "query": "from(bucket: \"openhab\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pmSensor_smartbuilding_1_pm10\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}