{
 "title": "Floor 3 Room 2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Energy consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"openhab\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /^[^_]+_f3_r2_consumption$/)\r\n"
    }
   ]
  },
  {
   "title": "Lights",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openhab\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lights_f3_r2_state\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "AC",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"openhab\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ac_f3_r2_state\")\r\n  |> last()"
    }
   ]
  }
 ]
}