version: '3'
services:
  jenkins:
    container_name: jenkins
    image: custom_jenkins
    ports:
      - 8084:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home: