version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - 8084:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home:rw

volumes:
  jenkins_home: